### ISSUE TITLE
iOS - libWindMeterSDKFat.a

### ISSUE THREAD

**Issue by cwalmsley** [WeatherFlow/WindMeterSDK#6]
Hi,

Is it possible to combine this file with libWindMeterSDK.a please? Currently its a pain point in my application to manually remove this file from the linked frameworks every time I switch between the simulator and a physical device.

Thanks,
Chris

**Comment by dtrauger** [comment]
Chris,

The "fat" library includes both the armv7 and arm64 architectures as well
as the i386 and x86_64 necessary to run in a simulator environemnt.  You
can freely use this variant instead of the non-fat library, they are
provided separately to give the developer the option to swap the binary to
reduce the overall app size.  You can check the architectures of the fat
library using the following:

lipo -info libWindMeterSDKFat.a

You should get output like:

Architectures in the fat file: libWindMeterSDKFat.a are: armv7 arm64 i386
x86_64

If you have any questions, please let me know.

Derek

**Comment by cwalmsley** [comment]
I see, thats great, I didn't realize this was the case.

Thanks!
Chris
